// nationalities.js

export const nationalities = [
  { label: "Afganistan", value: "Afganistan" },
  { label: "Afrika Selatan", value: "Afrika Selatan" },
  { label: "Albania", value: "Albania" },
  { label: "Aljazair", value: "Aljazair" },
  { label: "Amerika Serikat", value: "Amerika Serikat" },
  { label: "Andorra", value: "Andorra" },
  { label: "Angola", value: "Angola" },
  { label: "Antigua dan Barbuda", value: "Antigua dan Barbuda" },
  { label: "Arab Saudi", value: "Arab Saudi" },
  { label: "Argentina", value: "Argentina" },
  { label: "Armenia", value: "Armenia" },
  { label: "Australia", value: "Australia" },
  { label: "Austria", value: "Austria" },
  { label: "Azerbaijan", value: "Azerbaijan" },
  { label: "Bahama", value: "Bahama" },
  { label: "Bahrain", value: "Bahrain" },
  { label: "Bangladesh", value: "Bangladesh" },
  { label: "Barbados", value: "Barbados" },
  { label: "Belanda", value: "Belanda" },
  { label: "Belize", value: "Belize" },
  { label: "Benin", value: "Benin" },
  { label: "Bhutan", value: "Bhutan" },
  { label: "Bolivia", value: "Bolivia" },
  { label: "Bosnia dan Herzegovina", value: "Bosnia dan Herzegovina" },
  { label: "Botswana", value: "Botswana" },
  { label: "Brasil", value: "Brasil" },
  { label: "Brunei Darussalam", value: "Brunei Darussalam" },
  { label: "Burkina Faso", value: "Burkina Faso" },
  { label: "Burundi", value: "Burundi" },
  { label: "Butan", value: "Butan" },
  { label: "Ceko", value: "Ceko" },
  { label: "Chad", value: "Chad" },
  { label: "Chile", value: "Chile" },
  { label: "China", value: "China" },
  { label: "Colombia", value: "Colombia" },
  { label: "Komoros", value: "Komoros" },
  { label: "Kongo (Republik Kongo)", value: "Kongo (Republik Kongo)" },
  { label: "Korea Selatan", value: "Korea Selatan" },
  { label: "Kosta Rika", value: "Kosta Rika" },
  { label: "Kroasia", value: "Kroasia" },
  { label: "Kuba", value: "Kuba" },
  { label: "Kuwait", value: "Kuwait" },
  { label: "Kyrgyzstan", value: "Kyrgyzstan" },
  { label: "Laos", value: "Laos" },
  { label: "Lesotho", value: "Lesotho" },
  { label: "Latvia", value: "Latvia" },
  { label: "Lebanon", value: "Lebanon" },
  { label: "Liberia", value: "Liberia" },
  { label: "Libya", value: "Libya" },
  { label: "Liechtenstein", value: "Liechtenstein" },
  { label: "Lituania", value: "Lituania" },
  { label: "Luksemburg", value: "Luksemburg" },
  { label: "Madagaskar", value: "Madagaskar" },
  { label: "Maladewa", value: "Maladewa" },
  { label: "Malaysia", value: "Malaysia" },
  { label: "Malawi", value: "Malawi" },
  { label: "Malta", value: "Malta" },
  { label: "Maroko", value: "Maroko" },
  { label: "Mauritania", value: "Mauritania" },
  { label: "Mauritius", value: "Mauritius" },
  { label: "Mozambik", value: "Mozambik" },
  { label: "Myanmar", value: "Myanmar" },
  { label: "Namibia", value: "Namibia" },
  { label: "Nauru", value: "Nauru" },
  { label: "Nepal", value: "Nepal" },
  { label: "Niger", value: "Niger" },
  { label: "Nigeria", value: "Nigeria" },
  { label: "Nikaragua", value: "Nikaragua" },
  { label: "Norwegia", value: "Norwegia" },
  { label: "Oman", value: "Oman" },
  { label: "Pakistan", value: "Pakistan" },
  { label: "Palau", value: "Palau" },
  { label: "Panama", value: "Panama" },
  { label: "Papua Nugini", value: "Papua Nugini" },
  { label: "Paraguay", value: "Paraguay" },
  { label: "Peru", value: "Peru" },
  { label: "Polandia", value: "Polandia" },
  { label: "Portugal", value: "Portugal" },
  { label: "Prancis", value: "Prancis" },
  { label: "Qatar", value: "Qatar" },
  { label: "Rumania", value: "Rumania" },
  { label: "Rusia", value: "Rusia" },
  { label: "Rwanda", value: "Rwanda" },
  { label: "Saint Kitts dan Nevis", value: "Saint Kitts dan Nevis" },
  { label: "Saint Lucia", value: "Saint Lucia" },
  {
    label: "Saint Vincent dan Grenadines",
    value: "Saint Vincent dan Grenadines",
  },
  { label: "Samoa", value: "Samoa" },
  { label: "San Marino", value: "San Marino" },
  { label: "Sao Tome dan Principe", value: "Sao Tome dan Principe" },
  { label: "Senegal", value: "Senegal" },
  { label: "Serbia", value: "Serbia" },
  { label: "Seychelles", value: "Seychelles" },
  { label: "Sierra Leone", value: "Sierra Leone" },
  { label: "Singapura", value: "Singapura" },
  { label: "Slovakia", value: "Slovakia" },
  { label: "Slovenia", value: "Slovenia" },
  { label: "Somalia", value: "Somalia" },
  { label: "Spanyol", value: "Spanyol" },
  { label: "Sri Lanka", value: "Sri Lanka" },
  { label: "St. Kitts dan Nevis", value: "St. Kitts dan Nevis" },
  { label: "Sudan", value: "Sudan" },
  { label: "Sudan Selatan", value: "Sudan Selatan" },
  { label: "Suriname", value: "Suriname" },
  { label: "Swedia", value: "Swedia" },
  { label: "Switzerland", value: "Switzerland" },
  { label: "Syria", value: "Syria" },
  { label: "Tailand", value: "Tailand" },
  { label: "Taiwan", value: "Taiwan" },
  { label: "Tanjung Verde", value: "Tanjung Verde" },
  { label: "Timor Leste", value: "Timor Leste" },
  { label: "Togo", value: "Togo" },
  { label: "Tokelau", value: "Tokelau" },
  { label: "Tonga", value: "Tonga" },
  { label: "Trinidad dan Tobago", value: "Trinidad dan Tobago" },
  { label: "Tunisia", value: "Tunisia" },
  { label: "Turki", value: "Turki" },
  { label: "Turkmenistan", value: "Turkmenistan" },
  { label: "Tuvalu", value: "Tuvalu" },
  { label: "Uganda", value: "Uganda" },
  { label: "Ukraina", value: "Ukraina" },
  { label: "Uruguay", value: "Uruguay" },
  { label: "Uzbekistan", value: "Uzbekistan" },
  { label: "Vanuatu", value: "Vanuatu" },
  { label: "Venezuela", value: "Venezuela" },
  { label: "Vietnam", value: "Vietnam" },
  { label: "Yaman", value: "Yaman" },
  { label: "Yordania", value: "Yordania" },
  { label: "Yugoslavia", value: "Yugoslavia" },
  { label: "Zambia", value: "Zambia" },
  { label: "Zanzibar", value: "Zanzibar" },
  { label: "Zimbabwe", value: "Zimbabwe" },
];
