version: "2"
services:
  karoseri-frontendv2:
    image: localhost/karoseri-frontendv2:1.0.0
    build: .
    container_name: karoseri-frontendv2
    restart: unless-stopped
    volumes:
      - .env:/app/.env
      - ./src:/app/src
    ports:
      - "3030:3030"
networks:
  db:
    external: true
